host="sdf"
config_file="$LCLS_LATTICE/impact/models/sc_inj/v1/ImpactT.yaml"
distgen_input_file="$LCLS_LATTICE/distgen/models/sc_inj/vcc_image/distgen.yaml"
workdir="$SCRATCH"
summary_output_dir="/sdf/group/ard/thakur12/lume-impact-live-demo/summary"
#plot_output_dir="/gpfs/slac/staas/fs1/g/accelerator_modeling/cmayes/lume-impact-live-demo-data/plot"
plot_output_dir="/sdf/group/ard/thakur12/lume-impact-live-demo/plots/"

archive_dir="/sdf/group/ard/thakur12/lume-impact-live-demo/archive"
snapshot_dir="/sdf/group/ard/thakur12/lume-impact-live-demo/snapshot"
distgen_laser_file="/sdf/group/ard/impact/output/distgen_laser.txt"
num_procs=1
mpi_run_cmd="salloc --partition shared -N 1 -n {nproc} /sdf/sw/gcc-4.8.5/openmpi-4.0.4/bin/mpirun -n {nproc} {command_mpi}"
impact_command="/opt/conda/envs/lume-live-dev/bin/ImpactTexe"
impact_command_mpi="/opt/conda/envs/lume-live-dev/bin/ImpactTexe-mpi"