host="sdf"
config_file="$LCLS_LATTICE/impact/models/sc_inj/v1/ImpactT.yaml"
distgen_input_file="$LCLS_LATTICE/distgen/models/sc_inj/vcc_image/distgen.yaml"
workdir="$SCRATCH"
summary_output_dir="summary"
plot_output_dir="plots"

archive_dir="archive"
snapshot_dir="snapshot"
distgen_laser_file="/sdf/group/ard/impact/output/distgen_laser.txt"
num_procs=64
mpi_run_cmd="salloc --partition shared -N 1 -n {nproc}  /opt/conda/envs/lume-live-dev/bin/mpirun -n {nproc} {command_mpi}"
impact_command="/opt/conda/envs/lume-live-dev/bin/ImpactTexe"
impact_command_mpi="/opt/conda/envs/lume-live-dev/bin/ImpactTexe-mpi"